services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/meubanco

  frontend:
    build:
      context: ./frontend/projeto-email-front
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/projeto-email-front:/app
      - /app/node_modules
    working_dir: /app

  db:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: projeto_email
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
